### PR TITLE
Fixes all JSHint and JSCS errors

### LINKED ISSUE #62: Fix JSHint and JSCSRC error
https://travis-ci.org/beagleterm/beagle-term/jobs/159502150

### PR DESCRIPTION
**Pull request by RandomlyKnighted**
Fixes #62.

In preparation for our release on Thursday I thought it would be a good idea to go ahead and fix all our outstanding JSHint errors. This PR takes care of that. 

Unless there's some other bug or issue that needs to be taken care of this will be my last PR before Thursday's release.

### CODE REVIEW

**Comment by sunglim** [comment]
Awesome! Thank you! There're lots of errors.

**Comment by RandomlyKnighted** [comment]
@sunglim lots of errors in what? Are you referring to errors other than the ones that I just fixed?

**Comment by sunglim** [comment]
@RandomlyKnighted oh sorry. I mean there were lots of errors and you have fixed it :) 
Sorry about my bad English!

**Comment by RandomlyKnighted** [comment]
It's alright. Thanks for the clarification.

**Pull request merged**
