### PR TITLE
Adding a packing script

### PR DESCRIPTION
**Pull request by sunglim**
@RandomlyKnighted  when you have time.

 - Minify hterm lib and use it.
 - Added a packing script.

TEST = <root of repository> $> python tools/packing.py

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
I'll try to take a look at this tonight when I have more time.

**Comment by sunglim** [comment]
> I'll try to take a look at this tonight when I have more time.
Yep totally no problem :)

**Comment by RandomlyKnighted** [comment]
When I try to run the command `python tools/packing.py` I get the following error message:

```
C:\Users\tbhughes\Documents\projects\beagle-term>python tools/packing.py
Traceback (most recent call last):
  File "tools/packing.py", line 53, in <module>
  File "tools/packing.py", line 47, in main
  File "tools/packing.py", line 17, in installDependencies
  File "C:\Users\tbhughes\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\tbhughes\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\tbhughes\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\tbhughes\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

What file is it looking for?

**Comment by sunglim** [comment]
Oops, Sorry. It seems like that `subprocess.call` without option is failed on Windows machine[1]. I'll check and update on my Windows as well.

[1] http://stackoverflow.com/questions/3022013/windows-cant-find-the-file-on-subprocess-call

**Comment by sunglim** [comment]
Please take a look again when you have time.

**Comment by RandomlyKnighted** [comment]
The python script ran and didn't generate any errors, actually didn't tell me anything at all. So I wasn't sure if it had done anything. It'd be nice if we had something to print to the console so we know it's working. 

For example, the grunt-bower-task NPM package will print `grunt-bower:  copying bower_components/bootstrap/dist/css/bootstrap.css  -> /lib/css/bootstrap.css` when it copies a file. It'd be nice if we had something like this so we know it worked.  

I mean what if something failed but didn't generate an error in the console. You would never know it. Adding logs to the console like this could help diagnose a problem. What do you think?

**Comment by sunglim** [comment]
>I mean what if something failed but didn't generate an error in the console. You would never know it. Adding logs to the console like this could help diagnose a problem. What do you think?

You're exactly right. Thank you for leaving a comment.
Updated, Now this script will print below message.
image

**Comment by RandomlyKnighted** [comment]
I tried running the command `python tools\packing.py` again and but ended up getting a new error:

```
python tools\packing.py
packing.py >> Start bower install
Traceback (most recent call last):
  File "tools\packing.py", line 59, in <module>
    main()
  File "tools\packing.py", line 54, in main
    copyDeployFiles()
  File "tools\packing.py", line 38, in copyDeployFiles
    os.makedirs('deploy')
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'deploy'
```

There are a couple ways we could handle this problem. First option is to delete that folder and all subfolders/sub-files then start copying. The second option is to just overwrite any existing files. I'm not sure if one is better than the other, but I'm in favor of the first option. What do you think?

**Comment by sunglim** [comment]
Thank you for the comment.

I have met this error. And I dont want to handle .

This message is shown when there is already same directory. The problem
is sometimes we want to keep the old files. Well. So deletion without
user's selection is not good.
And the error message shows what the problem is.
If a user want he can delete manually.
What do you say?

2016년 9월 19일 월요일, Tyler Hughes<notifications@github.com>님이 작성한 메시지:

**Comment by RandomlyKnighted** [comment]
I'm not sure I follow. If you want to keep the existing files then why run the packing script at all? I thought the packing script was what we, the Beagle Term dev team, would use to get the project ready to upload to the Google Chrome App Store. If that's it's intended use then you really don't need to keep the old files at all.

**Comment by sunglim** [comment]
All right. make sense. 

Also, this `packing.py` will do more jobs(for example minify js). that means this script will modify original file. so keeping old files means nothing.

I'll update. Thank you for sharing wisdom!

**Comment by RandomlyKnighted** [comment]
Just a thought, why not copy the files to their destination then minify? I don't think we should be minifying original library files in their bower folder. Reason being, if we ever make a change to the bower config then the next time bower install is run we would lose our changes.

**Comment by sunglim** [comment]
Yep sure. I(we) am not going to minfy original library.
Just going to use jquery.min.js, bootstrap.min.js that each library already
provides.

The thing I am going to minify is only javascript file that we made.
(index.js, background.js for now)

2016년 9월 19일 월요일, Tyler Hughes<notifications@github.com>님이 작성한 메시지:

**Comment by RandomlyKnighted** [comment]
What's all the `bad indentation` errors that's showing up in the Travis CI log?

**Comment by sunglim** [comment]
@RandomlyKnighted  Sorry. I didn't config files that `pylint` should check.  Sorry I'm almost new in travis.
I'll update.

**Comment by RandomlyKnighted** [comment]
It's fine, I've just been keeping an eye on Travis and that threw me off. I didn't realize you were linting your Python script.

**Comment by sunglim** [comment]
Thank you for understanding.

**Comment by RandomlyKnighted** [comment]
Looks like Travis CI is happy now. Are you ready to merge?

**Comment by sunglim** [comment]
@RandomlyKnighted  Yep. Sorry to bother you. I was trying to config `travis.yml` for pylint.

**Comment by RandomlyKnighted** [comment]
Oh no you weren't bothering me. It's generally customary for people to get the Travis CI build to pass before submitting merging. For me this is just normal procedure.

**Pull request merged**
